import express from "express";
import multer from "multer";
import path from "path";
import fs from "fs";
import db from "../config/db.js";

const router = express.Router();

// Ensure the local upload folder target directory path disk space exists
const uploadDir = "./uploads";
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

// 🛠️ CONFIG MULTER STORAGE DISK STRATEGY
const storage = multer.diskStorage({
  destination: (_req, _file, cb) => {
    cb(null, uploadDir);
  },
  filename: (_req, file, cb) => {
    // Generates precise requested naming signature syntax: 1771239394162-category.png
    const ext = path.extname(file.originalname);
    cb(null, `${Date.now()}-category${ext}`);
  }
});

const upload = multer({ storage });

/* ==========================================================================
   ADVANCED CATEGORY CRUD ROUTES (WITH FORM DATA + FILE UPLOADS)
   ========================================================================== */

// 1. GET ALL CATEGORIES WITH LIVE PRODUCT COUNTS
router.get("/categories", async (_req, res) => {
  try {
    const [rows] = await db.execute(
      `SELECT 
        c.*, 
        COUNT(p.id) AS product_count,
        GROUP_CONCAT(p.name ORDER BY p.name ASC SEPARATOR ', ') AS product_names
       FROM categories c
       LEFT JOIN products p ON p.category_id = c.id
       GROUP BY c.id
       ORDER BY c.id ASC`
    );

    // Optional: Convert the comma-separated string into a clean array on the fly
    const categoriesWithArray = rows.map(row => ({
      ...row,
      product_names: row.product_names ? row.product_names.split(', ') : []
    }));

    res.json({ categories: categoriesWithArray });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Could not load categories." });
  }
});

// 2. CREATE A CATEGORY (Added upload.single middleware)
router.post("/categories", upload.single("imageFile"), async (req, res) => {
  try {
    const name = (req.body.name || "").trim();
    const slug = (req.body.slug || "").trim().toLowerCase();
    const description = (req.body.description || "").trim() || null;
    
    // Grabs unique file path string generated by Multer above
    const image = req.file ? req.file.filename : null;
    
    if (!name) return res.status(400).json({ error: "Category name is required." });
    if (!slug) return res.status(400).json({ error: "Category URL slug is required." });

    const [result] = await db.execute(
      "INSERT INTO categories (name, slug, description, image) VALUES (?, ?, ?, ?)", 
      [name, slug, description, image]
    );
    
    res.status(201).json({ 
      category: { id: result.insertId, name, slug, description, image, product_count: 0 } 
    });
  } catch (err) {
    if (err.code === "ER_DUP_ENTRY") {
      return res.status(409).json({ error: "A category with that name or slug already exists." });
    }
    console.error(err);
    res.status(500).json({ error: "Could not create category." });
  }
});

// 3. UPDATE A CATEGORY (Added upload.single middleware)
router.put("/categories/:id", upload.single("imageFile"), async (req, res) => {
  try {
    const name = (req.body.name || "").trim();
    const slug = (req.body.slug || "").trim().toLowerCase();
    const description = (req.body.description || "").trim() || null;

    if (!name) return res.status(400).json({ error: "Category name is required." });
    if (!slug) return res.status(400).json({ error: "Category URL slug is required." });

    // Look up previous state details image reference if fallback update skips adding a file swap
    const [current] = await db.execute("SELECT image FROM categories WHERE id = ?", [req.params.id]);
    if (!current.length) return res.status(404).json({ error: "Category not found." });
    
    let image = current[0].image;
    if (req.file) {
      image = req.file.filename;
    }

    const [result] = await db.execute(
      "UPDATE categories SET name = ?, slug = ?, description = ?, image = ? WHERE id = ?", 
      [name, slug, description, image, req.params.id]
    );
    
    if (result.affectedRows === 0) return res.status(404).json({ error: "Category not found." });

    const [rows] = await db.execute(
      `SELECT c.*, COUNT(p.id) AS product_count
       FROM categories c LEFT JOIN products p ON p.category_id = c.id
       WHERE c.id = ? GROUP BY c.id`,
      [req.params.id]
    );
    res.json({ category: rows[0] });
  } catch (err) {
    if (err.code === "ER_DUP_ENTRY") {
      return res.status(409).json({ error: "A category with that name or slug already exists." });
    }
    console.error(err);
    res.status(500).json({ error: "Could not update category." });
  }
});

// 4. SAFELY REMOVE A CATEGORY WITH RELATION CHECK
router.delete("/categories/:id", async (req, res) => {
  try {
    const [countRows] = await db.execute(
      "SELECT COUNT(*) AS count FROM products WHERE category_id = ?",
      [req.params.id]
    );
    const count = countRows[0].count;

    if (count > 0 && req.query.force !== "true") {
      return res.status(409).json({
        error: `${count} product(s) use this category. Delete anyway to unassign them, or move them first.`,
        productCount: count,
      });
    }

    const [result] = await db.execute("DELETE FROM categories WHERE id = ?", [req.params.id]);
    if (result.affectedRows === 0) return res.status(404).json({ error: "Category not found." });
    
    res.json({ message: "Category deleted successfully." });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Could not delete category." });
  }
});

export default router;